default: &default
  adapter: postgresql
  host: <%= ENV['PG_HOST'] %>
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  # In our current configuration, this could be managed with a pool of 20 (C*T). But by default having more will not cause problems.
  pool: 25
  timeout: 5000
  schema_search_path: public

development:
  <<: *default
  database: auth0_development

test:
  <<: *default
  database: auth0_test

staging:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
